package Program;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */

import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblJudul2 = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();
        btnTeori = new javax.swing.JButton();
        btnPenggunaan = new javax.swing.JButton();
        btnTentang = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        lblCopyright = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Aplikasi Steganografi");
        lblJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        lblJudul2.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        lblJudul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul2.setText("Algoritma Least Significant Bit");
        lblJudul2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 500, 50));

        btnMulai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMulai.setText("MULAI");
        btnMulai.setFocusPainted(false);
        btnMulai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 150, 50));

        btnTeori.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTeori.setText("TEORI");
        btnTeori.setFocusPainted(false);
        btnTeori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTeori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeoriActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeori, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 150, 50));

        btnPenggunaan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPenggunaan.setText("CARA PENGGUNAAN");
        btnPenggunaan.setFocusPainted(false);
        btnPenggunaan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPenggunaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenggunaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPenggunaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 250, 50));

        btnTentang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTentang.setText("TENTANG");
        btnTentang.setFocusPainted(false);
        btnTentang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentangActionPerformed(evt);
            }
        });
        getContentPane().add(btnTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 150, 50));

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setFocusPainted(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 150, 50));

        lblCopyright.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCopyright.setText("© 2020 - Ervan Rahadian Hakim -");
        getContentPane().add(lblCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 1260, 50));

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\msi\\Documents\\NetBeansProjects\\Steganografi\\Background.jpg")); // NOI18N
        lblBackground.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        UIManager.put("OptionPane.messageFont", new Font("Nirmala UI", Font.PLAIN, 18));
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah Anda ingin menutup aplikasi ?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        try {
            new Tentang().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_btnTentangActionPerformed

    private void btnPenggunaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggunaanActionPerformed
        try  {
            new Penggunaan().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_btnPenggunaanActionPerformed

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        try  {
            new Enkripsi().setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_btnMulaiActionPerformed

    private void btnTeoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeoriActionPerformed
        try  {
            new Teori().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTeoriActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);                   
                } catch (Exception ex) {
                    Logger.getLogger(Enkripsi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMulai;
    private javax.swing.JButton btnPenggunaan;
    private javax.swing.JButton btnTentang;
    private javax.swing.JButton btnTeori;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul2;
    // End of variables declaration//GEN-END:variables
}