package Program;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */

public class Penggunaan extends javax.swing.JFrame {
    
    public Penggunaan() throws IOException {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblCopyright = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnPilihan = new javax.swing.JMenu();
        mnKembali = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cara Penggunaan");
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 690));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        jTextPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n\t<font size=\"5\" face=\"Nirmala UI\">\n\t<p>Saat aplikasi dijalankan, akan muncul tampilan Menu Utama yang memuat pilihan Mulai, Cara Penggunaan, \n\tTentang dan Keluar. Pilihan Mulai digunakan untuk melakukan proses steganografi, pilihan Cara Penggunaan \n\tdigunakan untuk mengetahui cara menggunakan aplikasi ini, pilihan Tentang digunakan untuk mengetahui \n\tinformasi pada aplikasi ini dan pilihan Keluar digunakan untuk menutup aplikasi ini.</p><br>\n\t\n\t<b>Pilihan Mulai</b>\n\t<p>Pilihan Mulai memuat dua pilihan lain yaitu Menu Encode dan Menu Decode.</p><br>\n\t\n\t<b>Menu Encode</b>\n\t<p>Saat pilihan Mulai dijalankan, akan muncul tampilan form Encode untuk proses penyisipan pesan teks ke \n\tdalam citra digital, dengan cara memilih berkas gambar (cover image), memasukkan pesan teks pada \n\tText Field dan memasukkan password. Klik Button Encode kemudian berikan nama pada berkas gambar yang \n\takan disisipi (stego image).</p><br>\n\t\n\t<b>Menu Decode</b>\n\t<p>Untuk menampilkan form Decode, klik pilihan Decode pada Menu Bar. Form Decode digunakan untuk proses \n\tmendapatkan pesan dalam stego image, dengan cara memilih berkas gambar (stego image) dan \n\tmemasukkan password untuk verifikasi. Klik Button Decode untuk mendapatkan pesan teks.</p><br>\n\t\n\t<b>Pilihan Teori</b>\n\t<p>Pilihan ini digunakan untuk mengetahui informasi yang berkaitan dengan steganografi dan kriptografi.</p><br>\n\t\n\t<b>Pilihan Cara Penggunaan</b>\n\t<p>Pilihan ini digunakan untuk mengetahui cara menggunakan aplikasi, akan dijelaskan mengenai fitur-fitur yang \n\tterdapat pada aplikasi ini.</p><br>\n\t\n\t<b>Pilihan Tentang</b>\n\t<p>Pilihan ini digunakan untuk mengetahui informasi yang berkaitan dengan pemrogram dan aplikasi.</p><br>\n\t\n\t<b>Pilihan Keluar</b>\n\t<p>Pilihan ini digunakan untuk menutup aplikasi.</p>\n\t</font>\n  </body>\r\n</html>\r\n");
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 1000, 550));

        lblCopyright.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCopyright.setText("© 2020 - Ervan Rahadian Hakim -");
        getContentPane().add(lblCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 1260, 50));

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\msi\\Documents\\NetBeansProjects\\Steganografi\\Background2.jpg")); // NOI18N
        lblBackground.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 690));

        jMenuBar1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 30));

        mnPilihan.setText("Pilihan");
        mnPilihan.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        mnPilihan.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mnPilihan.setPreferredSize(new java.awt.Dimension(80, 30));

        mnKembali.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        mnKembali.setText("Kembali");
        mnKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKembaliActionPerformed(evt);
            }
        });
        mnPilihan.add(mnKembali);

        jMenuBar1.add(mnPilihan);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKembaliActionPerformed
        try {
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnKembaliActionPerformed

    /**
    * @param args the command line arguments
    */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Penggunaan().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Penggunaan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JMenuItem mnKembali;
    private javax.swing.JMenu mnPilihan;
    // End of variables declaration//GEN-END:variables
}